version: '3.8'

services:
  sudoku-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: sudoku-container
    restart: unless-stopped
    environment:
      - NODE_ENV=production